spring:
  application:
    name: checkoutservice

server:
  port: ${SERVER_PORT:8086}
  shutdown: graceful

clients:
  cart:
    base-url:
      ${CART_SERVICE_URL:http://localhost:8083}

  order:
    base-url:
      ${ORDER_SERVICE_URL:http://localhost:8084}

  payment:
    base-url:
      ${PAYMENT_SERVICE_URL:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
